import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Scene, Entity } from "aframe-react";
import { useScript } from "../useScript";

export default function Home() {
  const status = useScript("https://aframe.io/releases/1.3.0/aframe.min.js");
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {status === "ready" && (
          <Scene>
            <a-assets>
              <a-asset-item id="fafi" src="/fafi.gltf" />
            </a-assets>
            <Entity gltf-model="#fafi" />
          </Scene>
        )}
      </div>
    </div>
  );
}
